/**
 * Export compiler tests.
 *
 * Golden files, not assertions about substrings: the deliverable IS the text a
 * consumer commits, so the test that protects it has to compare the whole text. The
 * generation date is normalised out — it is provenance, not behaviour.
 *
 * The refusal tests are the load-bearing half. A compiler that emits a slightly wrong
 * expectation produces a green test in someone else's CI, which is exactly the
 * wrong-artifact failure the spec format exists to refuse; so every construct a target
 * cannot express has a test proving it throws and names itself.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadSpec } from "../spec/parse.mts";
import type { Spec, SpecStep } from "../spec/types.mts";
import {
  compileSpec,
  TARGET_NAMES,
  UnsupportedConstructError,
} from "./index.mts";
import { compile } from "./compiler.mts";
import { cssAttributeSelector } from "./locators.mts";
import { playwrightTarget } from "./targets/playwright.mts";
import { puppeteerTarget } from "./targets/puppeteer.mts";
import { cypressTarget } from "./targets/cypress.mts";

const here = dirname(fileURLToPath(import.meta.url));
const fixtureDir = join(here, "..", "..", "fixtures", "specs");
const goldenDir = join(here, "__golden__");

const FIXTURES = ["approve-an-order", "grammar-coverage"] as const;

/** Cypress cannot address a frame at all (see the target's own note), so the frame
 *  fixture is golden-tested on the two targets that can and refusal-tested on the one
 *  that cannot — rather than being left out of the goldens entirely. */
const FRAME_FIXTURE = "frame-coverage";
const FRAME_TARGETS = ["playwright", "puppeteer"] as const;

function fixture(name: string): Spec {
  return loadSpec(readFileSync(join(fixtureDir, `${name}.yaml`), "utf8"));
}

/** Provenance is a date; behaviour is not. */
function withoutDate(source: string): string {
  return source.replace(/ on "\d{4}-\d{2}-\d{2}"\./, " on <date>.");
}

for (const name of FIXTURES) {
  for (const target of TARGET_NAMES) {
    test(`golden — ${name} compiles to ${target}`, () => {
      const compiled = compileSpec(fixture(name), target, {
        specPath: `fixtures/specs/${name}.yaml`,
      });
      const golden = readFileSync(join(goldenDir, compiled.path!), "utf8");
      assert.equal(withoutDate(compiled.source), withoutDate(golden));
    });
  }
}

test("every generated file names its provenance in the first two lines", () => {
  for (const target of TARGET_NAMES) {
    const { source } = compileSpec(fixture("approve-an-order"), target, {
      specPath: "specs/approve-an-order.yaml",
      generatedOn: "2026-09-03",
    });
    const [first, second] = source.split("\n");
    assert.equal(
      first,
      '// Generated by Formic from "specs/approve-an-order.yaml" on "2026-09-03".',
    );
    assert.match(second, /regenerate this file, do not hand-edit it/);
  }
});

test("the suggested file name follows the target's own convention", () => {
  const spec = fixture("approve-an-order");
  assert.equal(
    compileSpec(spec, "playwright").path,
    "approve-an-order.spec.ts",
  );
  assert.equal(compileSpec(spec, "puppeteer").path, "approve-an-order.mjs");
  assert.equal(compileSpec(spec, "cypress").path, "approve-an-order.cy.js");
  assert.equal(
    compileSpec(spec, "cypress", { outDir: join("a", "b") }).path,
    join("a", "b", "approve-an-order.cy.js"),
  );
});

test("an assertion's fields are a conjunction — every one reaches the output", () => {
  // The spec's assert is an AND; dropping a field silently weakens the exported test.
  const { source } = compileSpec(fixture("grammar-coverage"), "playwright");
  assert.match(source, /toBeVisible\(\)/);
  assert.match(source, /toBeHidden\(\)/);
  assert.match(source, /toHaveText\("Order approved"\)/);
  assert.match(source, /toContainText\("approved"\)/);
});

test("a url assertion (exact) compiles for every target — a page-level fact, no locator needed", () => {
  const spec: Spec = {
    name: "probe",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "goto",
        target: "http://127.0.0.1:4173/orders",
        assert: { url: "http://127.0.0.1:4173/orders" },
      },
    ],
  };
  assert.match(
    compileSpec(spec, "playwright").source,
    /toHaveURL\("http:\/\/127\.0\.0\.1:4173\/orders"\)/,
  );
  assert.match(
    compileSpec(spec, "puppeteer").source,
    /expectUrlExact\("http:\/\/127\.0\.0\.1:4173\/orders"\)/,
  );
  assert.match(
    compileSpec(spec, "cypress").source,
    /cy\.url\(\)\.should\("eq", "http:\/\/127\.0\.0\.1:4173\/orders"\)/,
  );
});

test("a urlPrefix assertion compiles to a `new RegExp(...)` call, never a bare regex literal", () => {
  // A `/` in the value must never be able to close the regex literal early — routing
  // through `new RegExp(...)` sidesteps the escaping hazard entirely (see the cypress
  // exact-text-match test above for the bare-literal version of the same hazard).
  // The prefix text's own `.` is a regex metacharacter, so it is escaped before it is
  // anchored and quoted — `.` -> `\.` -> (quoted) `\\.` in the emitted source text.
  const spec: Spec = {
    name: "probe",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "goto",
        target: "http://127.0.0.1:4173/orders",
        assert: { urlPrefix: "http://127.0.0.1:4173/" },
      },
    ],
  };
  assert.ok(
    compileSpec(spec, "playwright").source.includes(
      'await expect(page).toHaveURL(new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/"));',
    ),
  );
  assert.ok(
    compileSpec(spec, "cypress").source.includes(
      'cy.url().should("match", new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/"));',
    ),
  );
  // Puppeteer's `expectUrlPrefix` runs `.startsWith()` at runtime, so the value passed
  // through is the plain string — no regex escaping needed on this target at all.
  assert.ok(
    compileSpec(spec, "puppeteer").source.includes(
      'await expectUrlPrefix("http://127.0.0.1:4173/");',
    ),
  );
});

test("a urlPattern assertion compiles to `new RegExp(<source>)` per target", () => {
  const spec: Spec = {
    name: "probe",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "goto",
        target: "http://127.0.0.1:4173/orders",
        assert: { urlPattern: "^http://127\\.0\\.0\\.1:4173/orders/\\d+$" },
      },
    ],
  };
  const emittedPattern =
    'new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/\\\\d+$")';
  assert.ok(
    compileSpec(spec, "playwright").source.includes(
      `await expect(page).toHaveURL(${emittedPattern});`,
    ),
  );
  assert.ok(
    compileSpec(spec, "cypress").source.includes(
      `cy.url().should("match", ${emittedPattern});`,
    ),
  );
  assert.ok(
    compileSpec(spec, "puppeteer").source.includes(
      'await expectUrlPattern("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/\\\\d+$");',
    ),
  );
});

test("a url assertion (one key per step) followed by an element assertion all survive compilation", () => {
  // An assert is EITHER page-level (exactly one of url/urlPrefix/urlPattern) OR
  // element-level, never both and never more than one url key at once — see the
  // validator's mutual-exclusivity and exactly-one rules. This is the shape a repaired
  // navigation proposal now takes: one url check per step, the element check on its
  // own step after them. Text verified directly against `compileSpec` output before
  // being pinned here (see the ticket-2 url tests above for the same discipline).
  const spec: Spec = {
    name: "probe",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "click",
        target: "#approve-button",
        assert: { url: "http://127.0.0.1:4173/orders/SO-4471/confirmation" },
      },
      {
        id: "st_2",
        index: 2,
        action: "waitFor",
        target: '[data-testid="confirmation"]',
        assert: { urlPrefix: "http://127.0.0.1:4173/orders/" },
      },
      {
        id: "st_3",
        index: 3,
        action: "waitFor",
        target: '[data-testid="confirmation"]',
        assert: {
          urlPattern:
            "^http://127\\.0\\.0\\.1:4173/orders/SO-\\d+/confirmation$",
        },
      },
      {
        id: "st_4",
        index: 4,
        action: "waitFor",
        target: '[data-testid="confirmation"]',
        assert: {
          testId: "confirmation",
          hasText: "Order approved",
          containsText: "approved",
        },
      },
    ],
  };

  const playwrightSource = compileSpec(spec, "playwright").source;
  assert.ok(
    playwrightSource.includes(
      'await expect(page).toHaveURL("http://127.0.0.1:4173/orders/SO-4471/confirmation");',
    ),
  );
  assert.ok(
    playwrightSource.includes(
      'await expect(page).toHaveURL(new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/"));',
    ),
  );
  assert.ok(
    playwrightSource.includes(
      'await expect(page).toHaveURL(new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/SO-\\\\d+/confirmation$"));',
    ),
  );
  assert.ok(
    playwrightSource.includes(
      'await expect(page.getByTestId("confirmation")).toBeVisible();',
    ),
  );
  assert.ok(
    playwrightSource.includes(
      'await expect(page.getByTestId("confirmation")).toHaveText("Order approved");',
    ),
  );
  assert.ok(
    playwrightSource.includes(
      'await expect(page.getByTestId("confirmation")).toContainText("approved");',
    ),
  );

  // The specific combined url calls, not a loose `/url/i` substring match — that
  // would still pass if one of the three had silently gone missing.
  const puppeteerSource = compileSpec(spec, "puppeteer").source;
  assert.ok(
    puppeteerSource.includes(
      'await expectUrlExact("http://127.0.0.1:4173/orders/SO-4471/confirmation");',
    ),
  );
  assert.ok(
    puppeteerSource.includes(
      'await expectUrlPrefix("http://127.0.0.1:4173/orders/");',
    ),
  );
  assert.ok(
    puppeteerSource.includes(
      'await expectUrlPattern("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/SO-\\\\d+/confirmation$");',
    ),
  );
  assert.ok(
    puppeteerSource.includes(
      'await expectHasText(page, \'[data-testid="confirmation"]\', "Order approved");',
    ),
  );
  assert.ok(
    puppeteerSource.includes(
      'await expectContainsText(page, \'[data-testid="confirmation"]\', "approved");',
    ),
  );

  const cypressSource = compileSpec(spec, "cypress").source;
  assert.ok(
    cypressSource.includes(
      'cy.url().should("eq", "http://127.0.0.1:4173/orders/SO-4471/confirmation");',
    ),
  );
  assert.ok(
    cypressSource.includes(
      'cy.url().should("match", new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/"));',
    ),
  );
  assert.ok(
    cypressSource.includes(
      'cy.url().should("match", new RegExp("^http://127\\\\.0\\\\.0\\\\.1:4173/orders/SO-\\\\d+/confirmation$"));',
    ),
  );
  assert.ok(
    cypressSource.includes(
      'cy.get(\'[data-testid="confirmation"]\').should("have.text", "Order approved");',
    ),
  );
  assert.ok(
    cypressSource.includes(
      'cy.get(\'[data-testid="confirmation"]\').should("contain.text", "approved");',
    ),
  );
});

test("REFUSAL — a wholly empty assertion (no locator, no element predicate, no url) is named, not skipped", () => {
  // A validated spec can never reach this — the validator requires one of the seven
  // fields — but the compiler takes a `Spec`, not just validated YAML.
  const spec = specWith({ assert: {} as SpecStep["assert"] });
  for (const emitter of [playwrightTarget, puppeteerTarget, cypressTarget]) {
    assert.throws(
      () => compile(spec, emitter, "spec.yaml", "2026-09-03"),
      (error: Error) => {
        assert.ok(error instanceof UnsupportedConstructError);
        assert.match(
          error.message,
          /it has neither testId, selector, role, text, nor url/,
        );
        return true;
      },
    );
  }
});

test("REFUSAL — an element predicate with no locator to bind to demands one, never approximates by dropping it", () => {
  const spec = specWith({ assert: { visible: true } as SpecStep["assert"] });
  for (const emitter of [playwrightTarget, puppeteerTarget, cypressTarget]) {
    assert.throws(
      () => compile(spec, emitter, "spec.yaml", "2026-09-03"),
      (error: Error) => {
        assert.ok(error instanceof UnsupportedConstructError);
        assert.match(
          error.message,
          /it has neither testId, selector, role, nor text/,
        );
        return true;
      },
    );
  }
});

test("REFUSAL — a mixed url+element assertion that bypasses validation is refused, not silently thinned", () => {
  // `compile` takes a `Spec` directly, so a hand-built mix the validator now rejects
  // can still reach it. Before this fix, the url check ran and the code returned
  // immediately afterward — `hasText` never got checked, and the emitted file
  // silently dropped it rather than refusing (the exact class Codex's review named).
  const spec = specWith({
    action: "goto",
    target: "http://127.0.0.1:4173/orders",
    assert: {
      url: "http://127.0.0.1:4173/orders",
      hasText: "Order approved",
    } as SpecStep["assert"],
  });
  for (const emitter of [playwrightTarget, puppeteerTarget, cypressTarget]) {
    assert.throws(
      () => compile(spec, emitter, "spec.yaml", "2026-09-03"),
      (error: Error) => {
        assert.ok(error instanceof UnsupportedConstructError);
        assert.match(
          error.message,
          /it has neither testId, selector, role, nor text/,
        );
        return true;
      },
    );
  }
});

/** A spec built by hand — the compiler takes a `Spec`, so it must refuse constructs a
 *  validated file could never carry as well as ones it could. */
function specWith(step: Partial<SpecStep>): Spec {
  return {
    name: "refusal",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_0001",
        index: 1,
        action: "click",
        target: "#go",
        ...step,
      } as SpecStep,
    ],
  };
}

function refusal(spec: Spec, target: "playwright" | "puppeteer" | "cypress") {
  try {
    compileSpec(spec, target);
  } catch (error) {
    assert.ok(
      error instanceof UnsupportedConstructError,
      `expected a refusal, got ${String(error)}`,
    );
    return error;
  }
  throw new Error(`${target} silently accepted an unsupported construct`);
}

test("REFUSAL — a step action outside the table is named, not skipped", () => {
  // Straight at `compile`: `compileSpec` validates first, and the validator rejects an
  // unknown action before the target tables ever see it. The tables' own refusal is the
  // second line of defence and needs its own proof that it still names the construct.
  const spec = specWith({ action: "hover" as SpecStep["action"] });
  for (const emitter of [playwrightTarget, puppeteerTarget, cypressTarget]) {
    assert.throws(
      () => compile(spec, emitter, "spec.yaml", "2026-09-03"),
      (error: Error) => {
        assert.ok(error instanceof UnsupportedConstructError);
        assert.match(error.message, /the step action `hover` is unsupported/);
        assert.match(
          error.message,
          new RegExp(`cannot export to ${emitter.name}`),
        );
        return true;
      },
    );
  }
});

test("REFUSAL — compileSpec validates, so an invalid spec never reaches a target", () => {
  // `Spec` is structural: this object type-checks, and the state-change rule is the
  // reason the format has a validator at all. Without this call the library would emit
  // a click with no assertion — a test that passes through the drift it exists to catch.
  const spec = specWith({ assert: undefined });
  assert.throws(
    () => compileSpec(spec, "playwright"),
    (error: Error) => {
      assert.equal(error.name, "SpecValidationError");
      assert.match(error.message, /changes state and must carry an assert/);
      return true;
    },
  );
});

test("REFUSAL — a testId carrying a control character, which no CSS escape covers", () => {
  const withControlCharacter = `current${String.fromCharCode(1)}user`;
  const spec = specWith({ assert: { testId: withControlCharacter } });
  // The spec-wide precondition catches it first, for every target — not just the two
  // whose CSS attribute selectors cannot carry it.
  for (const target of TARGET_NAMES) {
    assert.match(
      refusal(spec, target).message,
      /the assertion `testId` on step 1 is unsupported — it contains the control character U\+0001/,
    );
  }
  // The CSS-level refusal remains as the second line of defence for a direct caller.
  assert.match(
    JSON.stringify(
      cssAttributeSelector("data-testid", withControlCharacter, "cypress"),
    ),
    /contains the control character U\+0001/,
  );
});

test("REFUSAL — a key Cypress inherits from Object rather than declares", () => {
  // `CYPRESS_KEYS[key]` once read the prototype chain, so this threw a TypeError deep
  // in the emitter instead of refusing by name.
  const spec = specWith({
    action: "press",
    target: "#email",
    value: "constructor",
    assert: { testId: "current-user" },
  });
  assert.match(refusal(spec, "cypress").message, /the key "constructor"/);
});

test("REFUSAL — an implicit XPath selector, which CSS targets cannot express", () => {
  for (const selector of ["//button", "(//button)[1]"]) {
    const spec = specWith({ target: selector, assert: { testId: "ok" } });
    assert.match(
      compileSpec(spec, "playwright").source,
      /page\.click\("\(?\/\//,
    );
    for (const target of ["puppeteer", "cypress"] as const) {
      assert.match(refusal(spec, target).message, /an implicit XPath selector/);
    }
  }
});

test("spec-authored text cannot break out of a generated comment", () => {
  // A step id is human-authored and the parser carries it verbatim. Interpolated raw,
  // the newline below ended the `// step` comment and the rest became executable code.
  const spec = specWith({
    id: 'st_0001")\nprocess.exit(1);//',
    assert: { testId: "current-user" },
  });
  for (const target of TARGET_NAMES) {
    const { source } = compileSpec(spec, target, {
      specPath: "specs/a\nb.yaml",
    });
    for (const line of source.split("\n")) {
      assert.ok(
        !line.includes("process.exit(1)") || line.trimStart().startsWith("//"),
        `injected statement escaped its comment: ${line}`,
      );
    }
    assert.match(source, /\/\/ Generated by Formic from "specs\/a\\nb\.yaml"/);
  }
});

test("a cypress exact-text match escapes the regex delimiter", () => {
  // `/` closes a regex literal: unescaped, `a/b` emitted `cy.contains(/^a/b$/)`.
  const spec = specWith({
    assert: { text: "orders/approved", exact: true },
  });
  assert.match(
    compileSpec(spec, "cypress").source,
    /cy\.contains\(\/\^orders\\\/approved\$\/\)/,
  );
});

test("a header value cannot break out of the provenance comment either", () => {
  // `generatedOn` reaches the header the same way the spec path does, and a library
  // caller supplies it directly — so it gets the same treatment, not just the date the
  // CLI happens to pass.
  const { source } = compileSpec(
    specWith({ assert: { testId: "ok" } }),
    "cypress",
    {
      specPath: "specs/a.yaml",
      generatedOn: '2026-09-04"\nprocess.exit(1);//',
    },
  );
  const [header] = source.split("\n");
  assert.ok(
    header.startsWith("// Generated by Formic from"),
    `header was split by the injected newline: ${header}`,
  );
  assert.ok(
    !header.includes("\n") && header.includes("\\n"),
    `the newline reached the header raw: ${header}`,
  );
});

test("REFUSAL — a line terminator in text that lands in an emitted literal", () => {
  // CR and LF have no escape inside a regex literal and none inside a CSS attribute
  // value, so they are refused once for every target rather than approximated.
  const newline = String.fromCharCode(10);
  const carriageReturn = String.fromCharCode(13);
  const cases: Array<[string, Partial<SpecStep>]> = [
    [
      "the assertion `text`",
      { assert: { text: `orders${newline}approved`, exact: true } },
    ],
    [
      "the assertion `hasText`",
      { assert: { testId: "ok", hasText: `a${carriageReturn}b` } },
    ],
    [
      "the value of step 1",
      { action: "fill", value: `a${newline}b`, assert: { testId: "ok" } },
    ],
  ];
  for (const [what, step] of cases) {
    for (const target of TARGET_NAMES) {
      const message = refusal(specWith(step), target).message;
      assert.match(message, /control character U\+000[AD]/);
      assert.ok(
        message.includes(what),
        `expected ${what} to be named, got: ${message}`,
      );
    }
  }
});

test("a line SEPARATOR is escaped rather than refused — it has one", () => {
  // U+2028/U+2029 terminate a line in JavaScript but not in JSON, so JSON.stringify
  // leaves them bare. They are escapable, so the policy escapes them.
  // Substring match, not exact: puppeteer's `::-p-text()` has no whole-string mode and
  // would refuse for that unrelated reason.
  const spec = specWith({
    assert: { text: `orders${String.fromCharCode(0x2028)}approved` },
  });
  for (const target of TARGET_NAMES) {
    const { source } = compileSpec(spec, target);
    assert.ok(
      !source.includes(String.fromCharCode(0x2028)),
      `${target} emitted a raw U+2028`,
    );
    assert.match(source, /\\u2028/);
  }
});

test("the puppeteer text poll treats an absent element as not-yet, not as failure", () => {
  // page.$eval REJECTS when nothing matches, so an un-caught sample ended the poll on
  // the first transient rerender — where replay re-resolves its locator to the deadline.
  const { source } = compileSpec(
    specWith({ assert: { testId: "ok", hasText: "Approved" } }),
    "puppeteer",
  );
  assert.match(
    source,
    /try \{[\s\S]*scope\.\$eval[\s\S]*\} catch \{[\s\S]*return null;/,
  );
  assert.match(
    source,
    /if \(actual !== null && predicate\(actual, expected\)\) return;/,
  );
  assert.match(source, /actual === null \? "no matching element"/);
});

test("a CSS attribute value is escaped losslessly, never left to widen the selector", () => {
  // Unescaped, `x"], body, [` closed the attribute early and the selector also matched
  // `body` — the assertion then passed on a page that never contained the element.
  assert.equal(
    cssAttributeSelector("data-testid", 'x"], body, [', "cypress"),
    '[data-testid="x\\"], body, ["]',
  );
  assert.equal(
    cssAttributeSelector("data-testid", "a\\b", "puppeteer"),
    '[data-testid="a\\\\b"]',
  );

  // Through the emitters, not just the helper: a target that stopped routing its
  // attribute selectors through the escaper would pass the two assertions above.
  const spec = specWith({ assert: { testId: 'x"], body, [' } });
  for (const target of ["puppeteer", "cypress"] as const) {
    const { source } = compileSpec(spec, target);
    // The `"` inside the attribute survives as a backslash-escaped CSS quote, so the
    // selector still closes exactly once and cannot pick up `body`.
    assert.ok(
      source.includes('[data-testid="x\\\\"], body, ["]'),
      `${target} emitted an unescaped attribute value:\n${source}`,
    );
  }
});

test("REFUSAL — a role locator, where the target has no accessible-name locator", () => {
  const spec = specWith({
    assert: { role: "button", name: "Sign in", exact: true },
  });
  // Playwright has getByRole, so it must still compile.
  assert.match(
    compileSpec(spec, "playwright").source,
    /getByRole\("button", \{ name: "Sign in", exact: true \}\)/,
  );
  for (const target of ["puppeteer", "cypress"] as const) {
    assert.match(
      refusal(spec, target).message,
      /the assertion locator `role` is unsupported/,
    );
  }
});

test("REFUSAL — a Playwright-only selector engine in a step target", () => {
  const spec = specWith({
    target: "text=Sign in",
    assert: { testId: "current-user" },
  });
  assert.match(
    compileSpec(spec, "playwright").source,
    /page\.click\("text=Sign in"\)/,
  );
  for (const target of ["puppeteer", "cypress"] as const) {
    assert.match(
      refusal(spec, target).message,
      /uses a selector-engine prefix/,
    );
  }
});

test("REFUSAL — a Playwright-only pseudo-class in an assertion selector", () => {
  const spec = specWith({ assert: { selector: "li:has-text('SO-4472')" } });
  for (const target of ["puppeteer", "cypress"] as const) {
    assert.match(
      refusal(spec, target).message,
      /the `:has-text\(\)` pseudo-class/,
    );
  }
});

test("REFUSAL — a key Cypress `.type()` has no token for", () => {
  const spec = specWith({
    action: "press",
    target: "#email",
    value: "Tab",
    assert: { testId: "current-user" },
  });
  assert.match(
    compileSpec(spec, "playwright").source,
    /page\.press\("#email", "Tab"\)/,
  );
  assert.match(
    compileSpec(spec, "puppeteer").source,
    /keyboard\.press\("Tab"\)/,
  );
  assert.match(refusal(spec, "cypress").message, /the key "Tab"/);
});

test("REFUSAL — an exact text match, which puppeteer's ::-p-text cannot express", () => {
  const spec = specWith({ assert: { text: "Order approved", exact: true } });
  assert.match(
    compileSpec(spec, "playwright").source,
    /getByText\("Order approved", \{ exact: true \}\)/,
  );
  assert.match(
    compileSpec(spec, "cypress").source,
    /cy\.contains\(\/\^Order approved\$\/\)/,
  );
  assert.match(refusal(spec, "puppeteer").message, /an exact `text` assertion/);
});

test("REFUSAL — an unknown target name", () => {
  assert.throws(
    () => compileSpec(fixture("approve-an-order"), "selenium" as "playwright"),
    UnsupportedConstructError,
  );
});

test("the CLI rejects --out with no path instead of printing to stdout", () => {
  // `--out` with nothing after it used to fall through to the stdout branch and exit 0,
  // so a typo looked like a successful export that wrote no file.
  const cli = join(here, "..", "cli", "e2e-doctor.mts");
  const spec = join(fixtureDir, "approve-an-order.yaml");
  // import.meta.resolve already yields a file:// URL — the form Windows needs; handing
  // --import a bare `C:\...` path makes node read `c:` as an unsupported URL scheme.
  const run = (args: string[]) =>
    spawnSync(
      process.execPath,
      ["--import", import.meta.resolve("tsx"), cli, ...args],
      { encoding: "utf8" },
    );

  const missing = run(["export", spec, "--target", "cypress", "--out"]);
  assert.equal(missing.status, 2, missing.stderr);
  assert.match(missing.stderr, /--out requires a file path/);

  const flagShaped = run(["export", spec, "--out", "--target", "cypress"]);
  assert.equal(flagShaped.status, 2, flagShaped.stderr);
  assert.match(flagShaped.stderr, /--out requires a file path/);

  // The stdout path still works when --out is absent entirely.
  const toStdout = run(["export", spec, "--target", "cypress"]);
  assert.equal(toStdout.status, 0, toStdout.stderr);
  assert.match(toStdout.stdout, /describe\(/);
});

test("the emitted puppeteer and cypress files are syntactically valid JavaScript", () => {
  // Neither framework is installed here, so this is the strongest check available:
  // node's own parser on the exact text a consumer would commit.
  const dir = mkdtempSync(join(tmpdir(), "formic-export-"));
  for (const name of FIXTURES) {
    for (const target of ["puppeteer", "cypress"] as const) {
      const compiled = compileSpec(fixture(name), target, { outDir: dir });
      writeFileSync(compiled.path!, compiled.source);
      const checked = spawnSync(process.execPath, ["--check", compiled.path!], {
        encoding: "utf8",
      });
      assert.equal(
        checked.status,
        0,
        `${compiled.path} failed node --check:\n${checked.stderr}`,
      );
    }
  }
});

/**
 * The reference form, per target. The golden files hold the whole text; these assert
 * the two things a reader of the diff has to be able to check at a glance — that the
 * value is READ rather than embedded, and that the file says which variables it needs.
 */
test("a referenced value is read from the environment in every target", () => {
  const spec = fixture("grammar-coverage");
  const playwright = compileSpec(spec, "playwright").source;
  assert.match(
    playwright,
    /await page\.fill\("#password", process\.env\.GRAMMAR_COVERAGE_PASSWORD \?\? missingEnv\("GRAMMAR_COVERAGE_PASSWORD"\)\);/,
  );
  const puppeteer = compileSpec(spec, "puppeteer").source;
  assert.match(
    puppeteer,
    /await page\.type\("#password", process\.env\.GRAMMAR_COVERAGE_PASSWORD \?\? missingEnv\("GRAMMAR_COVERAGE_PASSWORD"\)\);/,
  );
  // Cypress commands run in the browser, which has no process environment of its own —
  // a Cypress project keeps its variables in `Cypress.env`.
  // `{ log: false }` keeps the resolved value out of the Cypress command log, which is
  // rendered into the run's own screenshots and video.
  const cypress = compileSpec(spec, "cypress").source;
  assert.match(
    cypress,
    /cy\.get\("#password"\)\.clear\(\)\.type\(Cypress\.env\("GRAMMAR_COVERAGE_PASSWORD"\) \?\? missingEnv\("GRAMMAR_COVERAGE_PASSWORD"\), \{ parseSpecialCharSequences: false, log: false \}\);/,
  );
  // Every generated file says what its own runner may still capture. The export leaves
  // the consumer's repository; a guarantee that only holds inside this harness has to
  // be stated where it stops holding.
  assert.match(playwright, /trace/i);
  assert.match(puppeteer, /trace|screenshot/i);
  assert.match(cypress, /screenshot|video/i);
  for (const source of [playwright, puppeteer, cypress]) {
    // The value never appears; the variable is named in the header so the person who
    // runs the file knows what to set.
    assert.match(source, /Requires these environment variables/);
    assert.match(source, /\/\/ {3}GRAMMAR_COVERAGE_PASSWORD/);
    assert.match(source, /missing (Cypress )?environment variable/);
  }
});

test("a spec with no reference gains neither the helper nor the header note", () => {
  for (const target of TARGET_NAMES) {
    const { source } = compileSpec(fixture("approve-an-order"), target);
    assert.doesNotMatch(source, /missingEnv/);
    assert.doesNotMatch(source, /Requires these environment variables/);
  }
});

test("REFUSAL — Cypress cannot press a key it will only learn at run time", () => {
  // `.type()` spells a key as a braced token chosen when the file is generated. Typing
  // the reference literally would send the key's SPELLING as text — a green test doing
  // the wrong thing, which is the class the refusals exist for.
  const spec = fixture("grammar-coverage");
  const referencedPress: Spec = {
    ...spec,
    steps: spec.steps.map((step: SpecStep) =>
      step.action === "press"
        ? { ...step, value: undefined, valueFrom: "env.SUBMIT_KEY" }
        : step,
    ),
  };
  assert.throws(
    () => compileSpec(referencedPress, "cypress"),
    (err: unknown) =>
      err instanceof UnsupportedConstructError &&
      /needs a key token chosen when the file is generated/.test(err.message),
  );
  // The other two send the key at run time, so they carry it through.
  assert.match(
    compileSpec(referencedPress, "playwright").source,
    /await page\.press\("#password", process\.env\.SUBMIT_KEY/,
  );
});

test("REFUSAL — a valueFrom no target can name is refused before any of them tries", () => {
  const spec = fixture("approve-an-order");
  const malformed: Spec = {
    ...spec,
    steps: spec.steps.map((step: SpecStep) =>
      step.target === "#email"
        ? { ...step, value: undefined, valueFrom: "vault.secrets/email" }
        : step,
    ),
  };
  // Two doors, and both are shut. `compileSpec` validates first, so a loaded spec
  // never reaches the walk; `compile` is the door a hand-built spec comes through.
  assert.throws(
    () => compileSpec(malformed, "playwright"),
    /valueFrom must match/,
  );
  for (const target of [playwrightTarget, puppeteerTarget, cypressTarget]) {
    assert.throws(
      () => compile(malformed, target, "hand-built.yaml", "2026-09-04"),
      (err: unknown) =>
        err instanceof UnsupportedConstructError &&
        /no target can read a source it cannot name/.test(err.message),
    );
  }
});

for (const target of FRAME_TARGETS) {
  test(`golden — ${FRAME_FIXTURE} compiles to ${target}`, () => {
    const compiled = compileSpec(fixture(FRAME_FIXTURE), target, {
      specPath: `fixtures/specs/${FRAME_FIXTURE}.yaml`,
    });
    const golden = readFileSync(join(goldenDir, compiled.path!), "utf8");
    assert.equal(withoutDate(compiled.source), withoutDate(golden));
  });
}

test("an all-selector frame chain compiles to Playwright's own frameLocator idiom", () => {
  // The idiom AND the stronger form: a FrameLocator re-resolves lazily and auto-waits on
  // every use, which is what the replay runner's timeout-bounded resolution does.
  const { source } = compileSpec(fixture(FRAME_FIXTURE), "playwright");
  assert.ok(
    source.includes(
      'await page.frameLocator("#checkout").frameLocator("#payment").locator("#card-number").fill("4242");',
    ),
    source,
  );
});

test("a chain naming a child frame goes through the lookup helper — frameLocator takes only a selector", () => {
  const { source } = compileSpec(fixture(FRAME_FIXTURE), "playwright");
  assert.ok(
    source.includes(
      'const frame3 = await frameChain(page, [{ selector: "#checkout" }, { name: "payment-frame" }]);',
    ),
    source,
  );
  assert.ok(source.includes('await frame3.locator("#pay").click();'), source);
  // The helper is emitted once, and only because this spec needs it.
  assert.equal(source.split("async function frameChain(").length - 1, 1);
  assert.ok(
    !compileSpec(fixture("grammar-coverage"), "playwright").source.includes(
      "frameChain",
    ),
  );
});

test("an assertion inherits its step's frame, and overrides it when it names one", () => {
  const { source } = compileSpec(fixture(FRAME_FIXTURE), "playwright");
  // Step 3 asserts in the frame its click happened in — no second resolution.
  assert.ok(
    source.includes(
      'await expect(frame3.getByTestId("receipt")).toBeVisible();',
    ),
    source,
  );
  // Step 5 clicks inside #checkout but asserts on a banner named by its own url.
  assert.ok(
    source.includes(
      'const assertFrame5 = await frameChain(page, [{ url: "http://127.0.0.1:4173/banner" }]);',
    ),
    source,
  );
  assert.ok(
    source.includes(
      'await expect(assertFrame5.getByTestId("host-banner")).toContainText("Thank you");',
    ),
    source,
  );
});

test("puppeteer scopes every command and every text poll to the resolved frame", () => {
  const { source } = compileSpec(fixture(FRAME_FIXTURE), "puppeteer");
  assert.ok(
    source.includes(
      'const frame2 = await frameChain([{ selector: "#checkout" }, { selector: "#payment" }]);',
    ),
    source,
  );
  assert.ok(
    source.includes('await frame2.type("#card-number", "4242");'),
    source,
  );
  assert.ok(
    source.includes(
      'await expectHasText(frame3, \'[data-testid="receipt"]\', "Paid");',
    ),
    source,
  );
});

test("REFUSAL — cypress refuses a frame chain by name rather than compiling it against the page", () => {
  // `cy.frameLoaded`/`cy.iframe` are a plugin, and the hand-rolled contentDocument idiom
  // gives up Cypress's own retrying resolution. Both are approximations, and an
  // approximation that goes green in the consumer's CI is the failure this refuses.
  assert.throws(
    () => compileSpec(fixture(FRAME_FIXTURE), "cypress"),
    (err: unknown) =>
      err instanceof UnsupportedConstructError &&
      err.target === "cypress" &&
      err.construct === "a frame chain" &&
      /no first-party way to address a nested browsing context/.test(
        err.message,
      ),
  );
});

test("a control character in a frame link is refused before any target sees it", () => {
  // Every frame value lands in an emitted string literal exactly as a locator does, and
  // a control character has no escape there — refused once, by name, for all targets.
  const spec: Spec = {
    name: "framed",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "click",
        target: "#go",
        frame: [{ name: `pay${String.fromCharCode(7)}ment` }],
        assert: { testId: "ok", visible: true },
      },
    ],
  };
  for (const target of TARGET_NAMES) {
    assert.throws(
      () => compileSpec(spec, target),
      (err: unknown) =>
        err instanceof UnsupportedConstructError &&
        /control character U\+0007/.test(err.message),
      `${target} must refuse a control character in a frame name`,
    );
  }
});

test("REFUSAL — a Playwright-only frame selector is refused by the plain-CSS targets", () => {
  // A frame link's `selector` addresses an <iframe> in a document, which is the same job
  // a step's `target` does — so it is held to the same per-target rules. It used to be
  // quoted and emitted unexamined, and `xpath=//iframe` compiled into a plain-CSS lookup
  // that matches nothing: a chain resolving no frame at run time, out of a compiler whose
  // whole contract is to refuse what a target cannot say.
  const spec: Spec = {
    name: "xpath-frame",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "click",
        target: "#pay",
        frame: [{ selector: "xpath=//iframe" }],
        assert: { testId: "receipt", visible: true },
      },
    ],
  };
  assert.throws(
    () => compileSpec(spec, "puppeteer"),
    (err: unknown) =>
      err instanceof UnsupportedConstructError &&
      err.target === "puppeteer" &&
      /a selector-engine prefix/.test(err.message),
  );
  // Playwright speaks its own selector syntax, so it emits the same chain unchanged.
  assert.ok(
    compileSpec(spec, "playwright").source.includes(
      'page.frameLocator("xpath=//iframe")',
    ),
  );
});

test("REFUSAL — a Playwright-only selector in a LOOKUP chain is refused too", () => {
  // The helper path builds a literal rather than a frameLocator expression; the check
  // belongs to the link, not to the shape the target happens to emit it in.
  const spec: Spec = {
    name: "xpath-frame-lookup",
    startUrl: "http://127.0.0.1:4173/",
    steps: [
      {
        id: "st_1",
        index: 1,
        action: "click",
        target: "#pay",
        frame: [{ selector: "#outer >> #inner" }, { name: "payment" }],
        assert: { testId: "receipt", visible: true },
      },
    ],
  };
  assert.throws(
    () => compileSpec(spec, "puppeteer"),
    (err: unknown) =>
      err instanceof UnsupportedConstructError &&
      /the `>>` engine chain/.test(err.message),
  );
});

test("both emitted frame helpers refuse an ambiguous link rather than taking the first", () => {
  // The rule belongs to the link, not to the runtime: an exported test that silently ran
  // in the wrong frame is the same wrong artifact, in someone else's CI where nobody is
  // watching for it.
  const playwright = readFileSync(
    join(goldenDir, "frame-coverage.spec.ts"),
    "utf8",
  );
  const puppeteer = readFileSync(join(goldenDir, "frame-coverage.mjs"), "utf8");
  for (const [name, source] of [
    ["playwright", playwright],
    ["puppeteer", puppeteer],
  ] as const) {
    assert.match(
      source,
      /is ambiguous/,
      `${name} must refuse an ambiguous link`,
    );
    assert.match(
      source,
      /matches > 1/,
      `${name} must decide on the COUNT, not on the first match`,
    );
    assert.ok(
      !/\.first\(\)|current\.\$\(link\.selector\)/.test(source),
      `${name} must not resolve a frame selector to its first match`,
    );
  }
});
