// Generated by Formic from "fixtures/specs/approve-an-order.yaml" on "2026-09-05".
// The spec is the source of truth: regenerate this file, do not hand-edit it.

describe("approve-an-order", () => {
  it("approve-an-order", () => {
    // step 1 ("st_8c28faa1")
    cy.visit("http://127.0.0.1:4173/");

    // step 2 ("st_d6304bf5")
    cy.get("#email").clear().type("ops@forgedepot.test");
    cy.get("#email").should("be.visible");

    // step 3 ("st_b1f495b5")
    cy.get("#password").clear().type("hunter2");
    cy.get("#password").should("be.visible");

    // step 4 ("st_6c4760ff")
    cy.get("#signin-button").click();
    cy.get('[data-testid="current-user"]').should("be.visible");
    cy.get('[data-testid="current-user"]').should("have.text", "ops@forgedepot.test");

    // step 5 ("st_3bfe602b")
    cy.get('[data-order-id="SO-4472"]').click();
    cy.get('[data-testid="detail-customer"]').should("be.visible");
    cy.get('[data-testid="detail-customer"]').should("have.text", "Contoso Rail");

    // step 6 ("st_b0ddf21c")
    cy.get("#note").clear().type("verified against PO 88120");
    cy.get("#note").should("be.visible");

    // step 7 ("st_28efd87b")
    cy.get("#approve-button").click();
    cy.get('[data-testid="confirmation"]').should("be.visible");
    cy.get('[data-testid="confirmation"]').should("have.text", "Order approved");
  });
});
