// Generated by Formic from "fixtures/specs/approve-an-order.yaml" on "2026-09-05".
// The spec is the source of truth: regenerate this file, do not hand-edit it.

import { expect, test } from "@playwright/test";

test("approve-an-order", async ({ page }) => {
  // step 1 ("st_8c28faa1")
  await page.goto("http://127.0.0.1:4173/");

  // step 2 ("st_d6304bf5")
  await page.fill("#email", "ops@forgedepot.test");
  await expect(page.locator("#email")).toBeVisible();

  // step 3 ("st_b1f495b5")
  await page.fill("#password", "hunter2");
  await expect(page.locator("#password")).toBeVisible();

  // step 4 ("st_6c4760ff")
  await page.click("#signin-button");
  await expect(page.getByTestId("current-user")).toBeVisible();
  await expect(page.getByTestId("current-user")).toHaveText("ops@forgedepot.test");

  // step 5 ("st_3bfe602b")
  await page.click('[data-order-id="SO-4472"]');
  await expect(page.getByTestId("detail-customer")).toBeVisible();
  await expect(page.getByTestId("detail-customer")).toHaveText("Contoso Rail");

  // step 6 ("st_b0ddf21c")
  await page.fill("#note", "verified against PO 88120");
  await expect(page.locator("#note")).toBeVisible();

  // step 7 ("st_28efd87b")
  await page.click("#approve-button");
  await expect(page.getByTestId("confirmation")).toBeVisible();
  await expect(page.getByTestId("confirmation")).toHaveText("Order approved");
});
