// Generated by Formic from "fixtures/specs/frame-coverage.yaml" on "2026-09-05".
// The spec is the source of truth: regenerate this file, do not hand-edit it.

import { expect, test } from "@playwright/test";
import type { Frame, Page } from "@playwright/test";

const FRAME_TIMEOUT_MS = 5000;
const FRAME_POLL_MS = 50;

type FrameLink = { selector?: string; name?: string; url?: string; urlPrefix?: string };

async function frameChain(page: Page, chain: FrameLink[]): Promise<Frame> {
  let current: Frame = page.mainFrame();
  const deadline = Date.now() + FRAME_TIMEOUT_MS;
  for (const [position, link] of chain.entries()) {
    let next: Frame | null = null;
    for (;;) {
      let matches = 0;
      if (link.selector !== undefined) {
        const locator = current.locator(link.selector);
        matches = await locator.count();
        if (matches === 1) {
          const element = await locator.elementHandle();
          next = element === null ? null : await element.contentFrame();
        }
      } else {
        const found = current.childFrames().filter((child) => {
          const url = child.url();
          if (link.name !== undefined) return child.name() === link.name;
          if (link.url !== undefined) return url === link.url;
          return url.startsWith(link.urlPrefix as string);
        });
        matches = found.length;
        next = found.length === 1 ? found[0] : null;
      }
      if (matches > 1) {
        throw new Error(
          `frame chain link ${position + 1} (${JSON.stringify(link)}) is ambiguous — ${matches} frames match`,
        );
      }
      if (next !== null) break;
      if (Date.now() >= deadline) break;
      await new Promise((resolve) => setTimeout(resolve, FRAME_POLL_MS));
    }
    if (next === null) {
      throw new Error(
        `frame chain link ${position + 1} (${JSON.stringify(link)}) did not resolve`,
      );
    }
    current = next;
  }
  return current;
}

test("frame-coverage", async ({ page }) => {
  // step 1 ("st_fc000001")
  await page.goto("http://127.0.0.1:4173/");

  // step 2 ("st_fc000002")
  await page.frameLocator("#checkout").frameLocator("#payment").locator("#card-number").fill("4242");
  await expect(page.frameLocator("#checkout").frameLocator("#payment").locator("#card-number")).toBeVisible();

  // step 3 ("st_fc000003")
  const frame3 = await frameChain(page, [{ selector: "#checkout" }, { name: "payment-frame" }]);
  await frame3.locator("#pay").click();
  await expect(frame3.getByTestId("receipt")).toBeVisible();
  await expect(frame3.getByTestId("receipt")).toHaveText("Paid");

  // step 4 ("st_fc000004")
  const frame4 = await frameChain(page, [{ urlPrefix: "http://127.0.0.1:4173/embed/" }]);
  await frame4.locator("#spinner").waitFor({ state: "visible" });

  // step 5 ("st_fc000005")
  await page.frameLocator("#checkout").locator("#confirm").click();
  const assertFrame5 = await frameChain(page, [{ url: "http://127.0.0.1:4173/banner" }]);
  await expect(assertFrame5.getByTestId("host-banner")).toBeVisible();
  await expect(assertFrame5.getByTestId("host-banner")).toContainText("Thank you");
});
