// Generated by Formic from "fixtures/specs/grammar-coverage.yaml" on "2026-09-05".
// The spec is the source of truth: regenerate this file, do not hand-edit it.
//
// Requires these environment variables (the spec references them rather
// than carrying their values):
//   GRAMMAR_COVERAGE_PASSWORD
//
// The referenced steps below pass `{ log: false }`, so the resolved values stay
// out of the Cypress command log — and therefore out of the screenshots and the
// video rendered from it. The page itself is still shown; treat a run's video as
// a secret if the field displays what was typed.

describe("grammar-coverage", () => {
  function missingEnv(name) {
    throw new Error("missing Cypress environment variable " + name + " — this spec reads a value from it");
  }
  it("grammar-coverage", () => {
    // step 1 ("st_gc000001")
    cy.visit("http://127.0.0.1:4173/");

    // step 2 ("st_gc000002")
    cy.get("#email").clear().type("ops@forgedepot.test");
    cy.get("#email").should("be.visible");

    // step 3 ("st_gc000003")
    cy.get("#password").type("{enter}");
    cy.get("#login-error").should("not.be.visible");

    // step 4 ("st_gc000004")
    cy.get("#order-list").should("be.visible");

    // step 5 ("st_gc000005")
    cy.get("#region").select("emea");
    cy.get("#region").should("be.visible");

    // step 6 ("st_gc000006")
    cy.get('[data-order-id="SO-4471"]').click();
    cy.contains("Northwind Traders").should("be.visible");

    // step 7 ("st_gc000007")
    cy.get("#approve-button").click();
    cy.url().should("eq", "http://127.0.0.1:4173/orders/SO-4471/confirmation");

    // step 8 ("st_gc000008")
    cy.get('[data-testid="confirmation"]').should("be.visible");
    cy.url().should("match", new RegExp("^http://127\\.0\\.0\\.1:4173/orders/"));

    // step 9 ("st_gc000009")
    cy.get('[data-testid="confirmation"]').should("be.visible");
    cy.url().should("match", new RegExp("^http://127\\.0\\.0\\.1:4173/orders/SO-\\d+/confirmation$"));

    // step 10 ("st_gc000010")
    cy.get('[data-testid="confirmation"]').should("be.visible");
    cy.get('[data-testid="confirmation"]').should("be.visible");
    cy.get('[data-testid="confirmation"]').should("have.text", "Order approved");
    cy.get('[data-testid="confirmation"]').should("contain.text", "approved");

    // step 11 ("st_gc000011")
    cy.get("#password").clear().type(Cypress.env("GRAMMAR_COVERAGE_PASSWORD") ?? missingEnv("GRAMMAR_COVERAGE_PASSWORD"), { parseSpecialCharSequences: false, log: false });
    cy.get("#password").should("be.visible");
  });
});
