// Generated by Formic from "fixtures/specs/grammar-coverage.yaml" on "2026-09-05".
// The spec is the source of truth: regenerate this file, do not hand-edit it.
//
// Requires these environment variables (the spec references them rather
// than carrying their values):
//   GRAMMAR_COVERAGE_PASSWORD
//
// A Playwright trace records the arguments of every action, so a trace taken on
// these steps holds the resolved values. Run with `trace: 'off'` (or discard the
// trace) for a suite that fills secrets, and treat any kept trace as a secret.

import { expect, test } from "@playwright/test";

function missingEnv(name: string): never {
  throw new Error(
    `missing environment variable ${name} — this test reads a value from it`,
  );
}

test("grammar-coverage", async ({ page }) => {
  // step 1 ("st_gc000001")
  await page.goto("http://127.0.0.1:4173/");

  // step 2 ("st_gc000002")
  await page.fill("#email", "ops@forgedepot.test");
  await expect(page.locator("#email")).toBeVisible();

  // step 3 ("st_gc000003")
  await page.press("#password", "Enter");
  await expect(page.locator("#login-error")).toBeHidden();

  // step 4 ("st_gc000004")
  await page.locator("#order-list").waitFor({ state: "visible" });

  // step 5 ("st_gc000005")
  await page.selectOption("#region", "emea");
  await expect(page.locator("#region")).toBeVisible();

  // step 6 ("st_gc000006")
  await page.click('[data-order-id="SO-4471"]');
  await expect(page.getByText("Northwind Traders", { exact: false })).toBeVisible();

  // step 7 ("st_gc000007")
  await page.click("#approve-button");
  await expect(page).toHaveURL("http://127.0.0.1:4173/orders/SO-4471/confirmation");

  // step 8 ("st_gc000008")
  await page.locator('[data-testid="confirmation"]').waitFor({ state: "visible" });
  await expect(page).toHaveURL(new RegExp("^http://127\\.0\\.0\\.1:4173/orders/"));

  // step 9 ("st_gc000009")
  await page.locator('[data-testid="confirmation"]').waitFor({ state: "visible" });
  await expect(page).toHaveURL(new RegExp("^http://127\\.0\\.0\\.1:4173/orders/SO-\\d+/confirmation$"));

  // step 10 ("st_gc000010")
  await page.locator('[data-testid="confirmation"]').waitFor({ state: "visible" });
  await expect(page.getByTestId("confirmation")).toBeVisible();
  await expect(page.getByTestId("confirmation")).toHaveText("Order approved");
  await expect(page.getByTestId("confirmation")).toContainText("approved");

  // step 11 ("st_gc000011")
  await page.fill("#password", process.env.GRAMMAR_COVERAGE_PASSWORD ?? missingEnv("GRAMMAR_COVERAGE_PASSWORD"));
  await expect(page.locator("#password")).toBeVisible();
});
