/**
 * The evidence page — a single self-contained HTML file a reviewer opens.
 *
 * It inlines rrweb-player (the replay half of the rrweb project) and the segments
 * themselves, so a committed artifact renders with no network and no build step, years
 * later. What it shows, in order: the audit fields, the outcome, the step-keyed spec
 * diff, then one player per segment — for a heal, the failed step BEFORE and the
 * repaired step AFTER, side by side — and the full step log.
 *
 * Nothing here is generated by a model. The page is a deterministic function of the
 * evidence record, which is the property that makes it evidence.
 */
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import type { StepRecord, EvidenceRecord, ReplaySegment } from "./types.mts";
import type { RepairProposal } from "../heal/types.mts";
import {
  proposedStepYaml,
  type UiDrift,
  type UntestedComponent,
} from "./coverage.mts";

const require = createRequire(import.meta.url);
const PLAYER_DIR = dirname(require.resolve("rrweb-player"));
const PLAYER_JS = readFileSync(
  join(PLAYER_DIR, "rrweb-player.umd.min.cjs"),
  "utf8",
);
const PLAYER_CSS = readFileSync(join(PLAYER_DIR, "style.min.css"), "utf8");

export const PRODUCT_NAME = "E2E Doctor";

export interface EvidenceAttemptView {
  attempt: number;
  proposal: RepairProposal;
  before: ReplaySegment | null;
  after: ReplaySegment | null;
  verification: EvidenceRecord | null;
}

export interface EvidencePageInput {
  specName: string;
  /** passed | failed | healed | needs-human | unhealed */
  outcome: string;
  initial: EvidenceRecord;
  attempts?: EvidenceAttemptView[];
  /** Lines from renderSpecDiff; empty when nothing changed. */
  diff?: string[];
  healer?: { name: string; modelVersion: string };
  /** Untested components from the green run — proposed steps, never applied. */
  untested?: UntestedComponent[];
  /** UI drift since the previous record of this spec, when one was found. */
  drift?: UiDrift;
}

/** Public caption when a green-run step has no matching pre-heal frame. */
export function missingShippedFrameNote(stepIndex: number): string {
  return `no frame — first seen in the healed run, step ${stepIndex}; frames are captured from the pre-heal record`;
}

function stepFrameCell(index: number, shipped: ReadonlySet<string>): string {
  const name = `step-${index}`;
  if (shipped.has(name)) {
    return `<a href="#step-${index}">step ${index}</a> · <a href="frames/${name}.png">frame</a>`;
  }
  return escape(missingShippedFrameNote(index));
}

function driftSection(
  drift: UiDrift | undefined,
  shipped: ReadonlySet<string>,
): string {
  if (!drift) return "";
  if (drift.steps.length === 0)
    return `<h2>UI drift <span class="verdict">none since ${escape(drift.previousDecisionId)} (${escape(drift.previousTimestamp)})</span></h2>`;
  const list = (nodes: { role: string; name: string }[]) =>
    nodes
      .map((n) => `<code>${escape(n.role)}</code> ${escape(n.name)}`)
      .join("<br>");
  const rows = drift.steps
    .map(
      (d) =>
        `<tr><td>${stepFrameCell(d.index, shipped)}</td><td>${list(d.added) || "—"}</td><td>${list(d.removed) || "—"}</td></tr>`,
    )
    .join("");
  return `<h2>UI drift <span class="verdict">since ${escape(drift.previousDecisionId)} (${escape(drift.previousTimestamp)})</span></h2>
<p class="subtitle">Interactive elements that appeared or disappeared in a step's end state since the previous run of this spec, even where the replay stayed green. From the accessibility snapshots; no model involved.</p>
<table class="drift"><thead><tr><th>step</th><th>appeared</th><th>disappeared</th></tr></thead><tbody>${rows}</tbody></table>`;
}

function untestedSection(
  untested: UntestedComponent[],
  shipped: ReadonlySet<string>,
): string {
  if (untested.length === 0) return "";
  const rows = untested
    .map(
      (c) =>
        `<tr><td><code>${escape(c.role)}</code> ${escape(c.name)}</td><td>${stepFrameCell(c.firstSeenIndex, shipped)}</td><td><pre>${escape(proposedStepYaml(c))}</pre></td></tr>`,
    )
    .join("");
  return `<h2>Untested components <span class="verdict">${untested.length} proposed step(s), not applied</span></h2>
<p class="subtitle">Interactive elements the app showed during this run that no spec step acts on. Derived from the accessibility snapshots, no model involved. Paste a proposal into the spec and write its assertion.</p>
<table class="untested"><thead><tr><th>component</th><th>first seen</th><th>proposed step</th></tr></thead><tbody>${rows}</tbody></table>`;
}

/** Every player on the page, in document order — the frame renderer walks these. */
export function frameNames(input: EvidencePageInput): string[] {
  const names: string[] = [];
  for (const attempt of input.attempts ?? []) {
    if (attempt.before) names.push(`attempt-${attempt.attempt}-before`);
    if (attempt.after) names.push(`attempt-${attempt.attempt}-after`);
  }
  for (const segment of input.initial.segments) {
    names.push(`step-${segment.stepIndex}`);
  }
  return names;
}

function escape(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Segments are embedded as JSON inside a <script type="application/json">; a `</`
 *  inside the payload would end the script early, so it is split. */
function jsonForScript(value: unknown): string {
  return JSON.stringify(value).replace(/<\//g, "<\\/");
}

function player(name: string, segment: ReplaySegment, caption: string): string {
  return `<figure class="player" id="${escape(name)}" data-frame="${escape(name)}">
  <figcaption>${escape(caption)} <span class="meta">step ${segment.stepIndex} · ${segment.action}${segment.preambleCount > 0 ? ` · ${segment.preambleCount} preamble event(s)` : ""}</span></figcaption>
  <div class="mount"></div>
  <script type="application/json" class="events">${jsonForScript(segment.events)}</script>
</figure>`;
}

function auditTable(record: EvidenceRecord): string {
  const rows: [string, string][] = [
    ["decision id", record.decisionId],
    ["timestamp", record.timestamp],
    ["system version", record.systemVersion],
    ["model version", record.modelVersion ?? "none (token-free run)"],
    ["driver", record.driver],
    ["session reference", record.sessionId ?? "none"],
    [
      "app host",
      record.host
        ? `${record.host.name} (${record.host.kind}) ${record.host.baseUrl}`
        : "not hosted by this run",
    ],
    ["recording", record.recording],
  ];
  return `<table class="audit">${rows
    .map(([k, v]) => `<tr><th>${escape(k)}</th><td>${escape(v)}</td></tr>`)
    .join("")}</table>`;
}

/** "—" for a missing value — lab metrics are track/trend only, never a budget or a
 *  failure, so absence must read as "not measured", not as a bare blank cell. */
function formatMetricValue(value: number | null, unit = "ms"): string {
  return value === null ? "—" : `${Math.round(value)}${unit}`;
}

/** A compact per-step metrics cell: a one-line summary (LCP/CLS/long-tasks — the
 *  numbers a reviewer scans first) with the full navigation/paint breakdown behind a
 *  details toggle, same pattern as the end-state snapshot cell below. */
function metricsCell(metrics: StepRecord["metrics"]): string {
  if (!metrics) return "—";
  const cls = metrics.cls === null ? "—" : metrics.cls.toFixed(3);
  const longTasks =
    metrics.longTasksCount === null ? "—" : String(metrics.longTasksCount);
  const summaryParts = [
    metrics.lcp !== null ? `LCP ${formatMetricValue(metrics.lcp)}` : null,
    `CLS ${cls}`,
    `LT ${longTasks}`,
  ].filter((part): part is string => part !== null);
  const detailRows: [string, string][] = [
    ["TTFB", formatMetricValue(metrics.ttfb)],
    ["DOM content loaded", formatMetricValue(metrics.domContentLoaded)],
    ["DOM complete", formatMetricValue(metrics.domComplete)],
    ["first paint", formatMetricValue(metrics.firstPaint)],
    ["first contentful paint", formatMetricValue(metrics.firstContentfulPaint)],
    ["LCP", formatMetricValue(metrics.lcp)],
    ["CLS", cls],
    [
      "long tasks",
      metrics.longTasksCount === null
        ? "—"
        : `${metrics.longTasksCount} (${formatMetricValue(metrics.longTasksMs)})`,
    ],
  ];
  return `<details class="metrics"><summary>${escape(summaryParts.join(" · "))}</summary><table class="audit">${detailRows
    .map(([k, v]) => `<tr><th>${escape(k)}</th><td>${escape(v)}</td></tr>`)
    .join("")}</table></details>`;
}

function stepLog(record: EvidenceRecord): string {
  const snapshotCell = (s: StepRecord) =>
    s.ariaSnapshot
      ? `<details class="snapshot"><summary>end state</summary><pre>${escape(s.ariaSnapshot)}</pre></details>`
      : "";
  return `<table class="steps"><thead><tr><th>#</th><th>action</th><th>target</th><th>inputs</th><th>started</th><th>ms</th><th>outcome</th><th>metrics</th><th>end state</th></tr></thead><tbody>${record.steps
    .map(
      (s) =>
        `<tr class="${s.outcome}"><td>${s.index}</td><td>${escape(s.action)}</td><td><code>${escape(s.target ?? "")}</code></td><td>${escape(s.inputs ? JSON.stringify(s.inputs) : "")}</td><td>${new Date(s.startedAt).toISOString()}</td><td>${s.endedAt - s.startedAt}</td><td>${escape(s.outcome)}${s.error ? `<pre>${escape(s.error)}</pre>` : ""}</td><td>${metricsCell(s.metrics)}</td><td>${snapshotCell(s)}</td></tr>`,
    )
    .join("")}</tbody></table>`;
}

function attemptSection(attempt: EvidenceAttemptView): string {
  const verdict = attempt.verification
    ? attempt.verification.outcome === "passed"
      ? "verified by a green replay"
      : "rejected — the replay still failed"
    : attempt.proposal.kind === "propose-assert-change"
      ? "for human review — not applied"
      : "declined";
  const players = [
    attempt.before
      ? player(
          `attempt-${attempt.attempt}-before`,
          attempt.before,
          "BEFORE — the step as it failed",
        )
      : "",
    attempt.after
      ? player(
          `attempt-${attempt.attempt}-after`,
          attempt.after,
          "AFTER — the repaired step, verified",
        )
      : "",
  ].join("\n");
  return `<section class="attempt">
  <h2>Attempt ${attempt.attempt}: ${escape(attempt.proposal.kind)} <span class="verdict">${escape(verdict)}</span></h2>
  <p class="reason">${escape(attempt.proposal.reason)}</p>
  <pre class="proposal">${escape(JSON.stringify(attempt.proposal, null, 2))}</pre>
  <div class="pair">${players}</div>
  ${attempt.verification ? `<details><summary>Verification run audit record</summary>${auditTable(attempt.verification)}${stepLog(attempt.verification)}</details>` : ""}
</section>`;
}

export function renderEvidencePage(input: EvidencePageInput): string {
  const attempts = input.attempts ?? [];
  const diff = input.diff ?? [];
  const shipped = new Set(frameNames(input));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escape(PRODUCT_NAME)} — ${escape(input.specName)} — ${escape(input.outcome)}</title>
<style>${PLAYER_CSS}</style>
<style>
  body { font: 14px/1.45 system-ui, sans-serif; margin: 0; padding: 24px; color: #1a1a1a; background: #fafafa; }
  h1 { margin: 0 0 4px; } h1 .outcome { font-size: 0.6em; padding: 2px 8px; border-radius: 4px; background: #ddd; vertical-align: middle; }
  .outcome.passed, .outcome.healed { background: #cfe9d6; } .outcome.failed, .outcome.unhealed { background: #f5c9c9; } .outcome.needs-human { background: #fde8b0; }
  .subtitle { color: #555; margin: 0 0 16px; }
  table { border-collapse: collapse; margin: 8px 0 16px; } th, td { text-align: left; padding: 4px 10px; border-bottom: 1px solid #e3e3e3; vertical-align: top; }
  table.audit th { color: #666; font-weight: 500; width: 9em; }
  tr.failed td { background: #fff1f1; } tr.healed td { background: #eefaf1; }
  pre { background: #f0f0f0; padding: 8px 10px; border-radius: 4px; overflow-x: auto; white-space: pre-wrap; }
  pre.diff .add { color: #1a7f37; } pre.diff .del { color: #b91c1c; }
  .pair { display: flex; gap: 16px; flex-wrap: wrap; }
  figure.player { margin: 0; flex: 1 1 480px; max-width: 100%; }
  figcaption { font-weight: 600; margin-bottom: 6px; } figcaption .meta { font-weight: 400; color: #666; }
  .mount { background: #fff; border: 1px solid #ddd; border-radius: 4px; overflow: hidden; }
  section.attempt { margin: 24px 0; padding-top: 12px; border-top: 2px solid #e3e3e3; }
  details.snapshot summary { cursor: pointer; color: #555; }
  details.snapshot pre { max-height: 240px; overflow: auto; font-size: 11px; margin: 4px 0 0; }
  details.metrics summary { cursor: pointer; color: #555; white-space: nowrap; }
  details.metrics table { margin: 4px 0 0; }
  .verdict { font-size: 0.7em; color: #555; font-weight: 400; }
  details { margin-top: 8px; }
</style>
</head>
<body>
<h1>${escape(input.specName)} <span class="outcome ${escape(input.outcome)}">${escape(input.outcome)}</span></h1>
<p class="subtitle">${escape(PRODUCT_NAME)} evidence${input.healer ? ` · healer ${escape(input.healer.name)} (${escape(input.healer.modelVersion)})` : " · token-free replay"}</p>
${auditTable(input.initial)}
${diff.length > 0 ? `<h2>Spec diff</h2><pre class="diff">${diff.map((l) => `<span class="${l.startsWith("+") ? "add" : "del"}">${escape(l)}</span>`).join("\n")}</pre>` : ""}
${attempts.map(attemptSection).join("\n")}
${driftSection(input.drift, shipped)}
${untestedSection(input.untested ?? [], shipped)}
<h2>${attempts.length > 0 ? "Initial run" : "Run"} — one replay segment per step</h2>
${input.initial.recording === "unavailable" ? `<p><em>The ${escape(input.initial.driver)} backend could not record a replay stream for this run; the step log below is the evidence.</em></p>` : ""}
<div class="pair">${input.initial.segments.map((s) => player(`step-${s.stepIndex}`, s, `Step ${s.stepIndex}`)).join("\n")}</div>
${stepLog(input.initial)}
<script>${PLAYER_JS}</script>
<script>
(() => {
  const PlayerModule = window.rrwebPlayer;
  const Player = PlayerModule && (PlayerModule.default || PlayerModule);
  const figures = Array.from(document.querySelectorAll("figure.player"));
  for (const figure of figures) {
    const events = JSON.parse(figure.querySelector("script.events").textContent);
    const mount = figure.querySelector(".mount");
    const width = Math.min(mount.clientWidth || 640, 640);
    const player = new Player({ target: mount, props: { events, width, height: Math.round(width * 0.62), autoPlay: false, showController: true, skipInactive: true } });
    const last = events[events.length - 1].timestamp - events[0].timestamp;
    // Show the END state of the segment: what the user saw when the step settled.
    // One millisecond PAST the last event: the player's seek does not apply an event
    // at exactly the seek offset, and the last event of a step's window is often the
    // one that matters (measured: an inserted confirming click's AFTER frame lacked
    // the interstitial its own final mutation revealed).
    try { player.goto(last + 1, false); } catch (e) { /* older player builds: leave at start */ }
    figure.dataset.ready = "1";
  }
  window.__e2edocReady = true;
})();
</script>
</body>
</html>
`;
}
